(function(g){var window=this;var tDa=function(a,b){return g.Xb(a,b)},m6=function(a){g.Rm(a,"zx",g.zb());
return a},n6=function(a,b,c){g.za(c)||(c=[String(c)]);
g.Um(a.o,b,c)},uDa=function(a,b){var c=[];
g.Fk(b,function(a){try{var b=g.uD.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.u(b)?g.tD(b)&&c.push(a):c.push(a)},a);
return c},vDa=function(a,b){var c=uDa(a,b);
(0,g.C)(c,function(a){g.uD.prototype.remove.call(this,a)},a)},wDa=function(a){if(a.Ed){if(a.Ed.locationOverrideToken)return{locationOverrideToken:a.Ed.locationOverrideToken};
if(null!=a.Ed.latitudeE7&&null!=a.Ed.longitudeE7)return{latitudeE7:a.Ed.latitudeE7,longitudeE7:a.Ed.longitudeE7}}return null},xDa=function(a,b,c,d){var e=new g.Im(null,void 0);
a&&g.Jm(e,a);b&&g.Km(e,b);c&&g.Lm(e,c);d&&g.Mm(e,d);return e},yDa=function(a){g.iG[a]&&(a=g.iG[a],(0,g.C)(a,function(a){g.gG[a]&&delete g.gG[a]}),a.length=0)},zDa=function(a){var b=g.fG();
if(b)if(b.clear(a),a)yDa(a);else for(var c in g.iG)yDa(c)},o6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.Cm;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",ADa(this,a.capabilities||""),BDa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",
this.o=a.localChannelEncryptionKey||"")},ADa=function(a,b){a.capabilities.clear();
(0,g.Ud)(b.split(","),g.Fa(tDa,CDa)).forEach(function(b){a.capabilities.add(b)})},BDa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},p6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},q6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},DDa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},EDa=function(a){return new p6(a)},FDa=function(a){return g.za(a)?(0,g.I)(a,EDa):[]},r6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},s6=function(a){return g.za(a)?"["+(0,g.I)(a,r6).join(",")+"]":"null"},t6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},GDa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},u6=function(a,b){return g.La(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},v6=function(a,b){return g.La(a,function(a){return q6(a,b)})},HDa=function(){var a=(0,g.eH)();
a&&vDa(a,a.o.Zd(!0))},w6=function(){var a=g.hH("yt-remote-connected-devices")||[];
g.gb(a);return a},IDa=function(a){if(g.Qa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},JDa=function(a){g.gH("yt-remote-connected-devices",a,86400)},y6=function(){if(x6)return x6;
var a=g.hH("yt-remote-device-id");a||(a=t6(),g.gH("yt-remote-device-id",a,31536E3));for(var b=w6(),c=1,d=a;g.Pa(b,d);)c++,d=a+"#"+c;return x6=d},z6=function(){var a=w6(),b=y6();
g.Pa(a,b);g.jH()&&g.kb(a,b);a=IDa(a);if(g.Qa(a))try{g.RG("remote_sid")}catch(c){}else try{g.QG("remote_sid",a.join(","),-1)}catch(c){}},KDa=function(){return g.hH("yt-remote-session-browser-channel")},LDa=function(){return g.hH("yt-remote-local-screens")||[]},MDa=function(){g.gH("yt-remote-lounge-token-expiration",!0,86400)},NDa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(LDa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.qm)(c,function(a){return!g.Pa(b,a)})&&MDa();
g.gH("yt-remote-local-screens",a,31536E3)},ODa=function(a,b){g.gH("yt-remote-session-browser-channel",a);
g.gH("yt-remote-session-screen-id",b);var c=w6(),d=y6();g.Pa(c,d)||c.push(d);JDa(c);z6()},A6=function(a){a||(g.iH("yt-remote-session-screen-id"),g.iH("yt-remote-session-video-id"));
z6();a=w6();g.Ua(a,y6());JDa(a)},PDa=function(){if(!B6){var a=g.FD();
a&&(B6=new g.oD(a))}return B6?!!B6.get("yt-remote-use-staging-server"):!1},QDa=function(){var a=window.document.createElement("a");
g.id(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Db(a)},RDa=function(a,b){var c=g.Md("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.jd(c,g.ke("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},SDa=function(){var a=QDa(),b=window.document.getElementById(a),c=b&&g.rF(b,"loaded");
c||b&&!c||(b=RDa(a,function(){g.rF(b,"loaded")||(g.qF(b,"loaded","true"),g.mG(a),g.nE(g.Fa(zDa,a),0))}))},C6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},TDa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},D6=function(a){a.length?UDa(a.shift(),function(){D6(a)}):E6()},VDa=function(a){return"chrome-extension://"+a+F6},UDa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},G6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},E6=function(){var a=TDa();
a&&a(!1,"No cast extension found")},H6=function(){if(WDa){var a=2,b=TDa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;UDa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",E6,c)}},XDa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(H6(),a({command:"cast.sender.init"}))},YDa=function(){H6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);D6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+F6,"//www.gstatic.com/eureka/clank"+F6])},I6=function(a,b,c){g.M.call(this);
this.F=null!=c?(0,g.A)(a,c):a;this.wd=b;this.D=(0,g.A)(this.CK,this);this.o=!1;this.A=0;this.B=this.Fa=null;this.C=[]},J6=function(){},K6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Y=new g.Ym(this);this.A=new g.Dg;this.A.setInterval(250)},$Da=function(a,b,c){a.Zj=1;
a.zh=m6(b.clone());a.fj=c;a.D=!0;ZDa(a,null)},L6=function(a,b,c,d,e){a.Zj=1;
a.zh=m6(b.clone());a.fj=null;a.D=c;e&&(a.CE=!1);ZDa(a,d)},ZDa=function(a,b){a.Qk=(0,g.G)();
M6(a);a.bi=a.zh.clone();n6(a.bi,"t",a.F);a.kn=0;a.Rc=a.o.Zr(a.o.Xm()?b:null);0<a.Ps&&(a.gq=new g.il((0,g.A)(a.SF,a,a.Rc),a.Ps));a.Y.W(a.Rc,"readystatechange",a.bW);var c=a.Ei?g.fc(a.Ei):{};a.fj?(a.Vq="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Rc.send(a.bi,a.Vq,a.fj,c)):(a.Vq="GET",a.CE&&!g.Id&&(c.Connection="close"),a.Rc.send(a.bi,a.Vq,null,c));a.o.Bf(1)},cEa=function(a,b,c){for(var d=!0;!a.pi&&a.kn<c.length;){var e=aEa(a,c);
if(e==N6){4==b&&(a.Ah=4,O6(15),d=!1);break}else if(e==bEa){a.Ah=4;O6(16);d=!1;break}else P6(a,e)}4==b&&0==c.length&&(a.Ah=1,O6(17),d=!1);a.Hf=a.Hf&&d;d||(Q6(a),R6(a))},aEa=function(a,b){var c=a.kn,d=b.indexOf("\n",c);
if(-1==d)return N6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return bEa;d+=1;if(d+c>b.length)return N6;var e=b.substr(d,c);a.kn=d+c;return e},eEa=function(a,b){a.Qk=(0,g.G)();
M6(a);var c=b?window.location.hostname:"";a.bi=a.zh.clone();g.Rm(a.bi,"DOMAIN",c);g.Rm(a.bi,"t",a.F);try{a.If=new window.ActiveXObject("htmlfile")}catch(n){Q6(a);a.Ah=7;O6(22);R6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in S6)k=S6[l];else if(l in dEa)k=S6[l]=dEa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=S6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.kd(g.Cc("b/12014412"),d);a.If.open();a.If.write(g.bd(c));a.If.close();a.If.parentWindow.m=(0,g.A)(a.hV,a);a.If.parentWindow.d=(0,g.A)(a.LD,a,!0);a.If.parentWindow.rpcClose=(0,g.A)(a.LD,a,!1);c=a.If.createElement("DIV");a.If.parentWindow.document.body.appendChild(c);d=g.Rc(a.bi.toString());d=g.sb(g.Oc(d));d=g.kd(g.Cc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.hd(c,g.bd(d));a.o.Bf(1)},
M6=function(a){a.yw=(0,g.G)()+a.C;
fEa(a,a.C)},fEa=function(a,b){if(null!=a.ll)throw Error("WatchDog timer not null");
a.ll=T6((0,g.A)(a.xV,a),b)},U6=function(a){a.ll&&(g.x.clearTimeout(a.ll),a.ll=null)},R6=function(a){a.o.Pz()||a.pi||a.o.Rp(a)},Q6=function(a){U6(a);
g.lf(a.gq);a.gq=null;a.A.stop();g.dn(a.Y);if(a.Rc){var b=a.Rc;a.Rc=null;b.abort();b.dispose()}a.If&&(a.If=null)},P6=function(a,b){try{a.o.DD(a,b),a.o.Bf(4)}catch(c){}},hEa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;gEa(a,b,function(e){e?c(!0):g.x.setTimeout(function(){hEa(a,b,c,d,f)},f)})}},gEa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{V6(d),c(!0)}catch(e){}};
d.onerror=function(){try{V6(d),c(!1)}catch(e){}};
d.onabort=function(){try{V6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{V6(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},V6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},iEa=function(a){this.o=a;
this.A=new J6},jEa=function(a){var b=W6(a.o,a.ul,"/mail/images/cleardot.gif");
m6(b);hEa(b.toString(),5E3,(0,g.A)(a.GJ,a),3,2E3);a.Bf(1)},Y6=function(a){var b=a.o.J;
if(null!=b)O6(5),b?(O6(11),X6(a.o,a,!1)):(O6(12),X6(a.o,a,!0));else if(a.Be=new K6(a,void 0,void 0,void 0),a.Be.Ei=a.Ns,b=a.o,b=W6(b,b.Xm()?a.Ul:null,a.Os),O6(5),!g.Gd||g.vc(10))n6(b,"TYPE","xmlhttp"),L6(a.Be,b,!1,a.Ul,!1);else{n6(b,"TYPE","html");var c=a.Be;a=!!a.Ul;c.Zj=3;c.zh=m6(b.clone());eEa(c,a)}},Z6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new J6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},kEa=function(a,b){this.o=a;
this.map=b;this.context=null},lEa=function(a){g.nf.call(this,"statevent",a)},mEa=function(a,b){g.nf.call(this,"timingevent",a);
this.size=b},nEa=function(a){g.nf.call(this,"serverreachability",a)},qEa=function(a){oEa(a);
if(3==a.o){var b=a.Gm++,c=a.xo.clone();g.Rm(c,"SID",a.B);g.Rm(c,"RID",b);g.Rm(c,"TYPE","terminate");$6(a,c);b=new K6(a,a.B,b,void 0);b.Zj=2;b.zh=m6(c.clone());(new window.Image).src=b.zh;b.Qk=(0,g.G)();M6(b)}pEa(a)},rEa=function(a){a.cK(1,0);
a.xo=W6(a,null,a.Ms);a7(a)},oEa=function(a){a.nh&&(a.nh.abort(),a.nh=null);
a.wc&&(a.wc.cancel(),a.wc=null);a.zg&&(g.x.clearTimeout(a.zg),a.zg=null);b7(a);a.fe&&(a.fe.cancel(),a.fe=null);a.rh&&(g.x.clearTimeout(a.rh),a.rh=null)},sEa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new kEa(a.UQ++,b));2!=a.o&&3!=a.o||a7(a)},a7=function(a){a.fe||a.rh||(a.rh=T6((0,g.A)(a.JD,a),0),a.Nj=0)},uEa=function(a,b){if(1==a.o){if(!b){a.Gm=Math.floor(1E5*Math.random());
var c=a.Gm++,d=new K6(a,"",c,void 0);d.Ei=null;var e=c7(a),f=a.xo.clone();g.Rm(f,"RID",c);g.Rm(f,"CVER","1");$6(a,f);$Da(d,f,e);a.fe=d;a.o=2}}else 3==a.o&&(b?tEa(a,b):0==a.A.length||a.fe||tEa(a))},tEa=function(a,b){if(b)if(6<a.si){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.Gm-1;var d=c7(a)}else c=b.G,d=b.fj;else c=a.Gm++,d=c7(a);var e=a.xo.clone();g.Rm(e,"SID",a.B);g.Rm(e,"RID",c);g.Rm(e,"AID",a.nk);$6(a,e);c=new K6(a,a.B,c,a.Nj+1);c.Ei=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.fe=c;$Da(c,e,d)},$6=function(a,b){if(a.ud){var c=a.ud.wz();
c&&g.Mb(c,function(a,c){g.Rm(b,c,a)})}},c7=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.si&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.si?e:f-d;try{g.Mb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},vEa=function(a){a.wc||a.zg||(a.G=1,a.zg=T6((0,g.A)(a.ID,a),0),a.Bj=0)},d7=function(a){if(a.wc||a.zg||3<=a.Bj)return!1;
a.G++;a.zg=T6((0,g.A)(a.ID,a),wEa(a,a.Bj));a.Bj++;return!0},X6=function(a,b,c){a.Uq=c;
a.Wf=b.Lg;a.F||rEa(a)},b7=function(a){null!=a.ti&&(g.x.clearTimeout(a.ti),a.ti=null)},wEa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},e7=function(a,b){if(2==b||9==b){var c=null;
a.ud&&(c=null);var d=(0,g.A)(a.WW,a);c||(c=new g.Im("//www.google.com/images/cleardot.gif"),m6(c));gEa(c.toString(),1E4,d)}else O6(2);xEa(a,b)},xEa=function(a,b){a.o=0;
a.ud&&a.ud.qy(b);pEa(a);oEa(a)},pEa=function(a){a.o=0;
a.Wf=-1;if(a.ud)if(0==a.C.length&&0==a.A.length)a.ud.Nr();else{g.Xa(a.C);var b=g.Xa(a.A);a.C.length=0;a.A.length=0;a.ud.Nr(b)}},W6=function(a,b,c){var d=g.Sm(c);
if(""!=d.A)b&&g.Km(d,b+"."+d.A),g.Lm(d,d.D);else{var e=window.location;d=xDa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Gl&&g.Mb(a.Gl,function(a,b){g.Rm(d,b,a)});
g.Rm(d,"VER",a.si);$6(a,d);return d},T6=function(a,b){if(!g.Ba(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},O6=function(a){f7.dispatchEvent(new lEa(f7,a))},yEa=function(){},zEa=function(a,b){this.action=a;
this.params=b||{}},g7=function(a,b){g.M.call(this);
this.o=new g.ou(this.YU,0,this);g.N(this,this.o);this.wd=5E3;this.A=0;if(g.Ba(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ba(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},h7=function(a,b,c){this.L=a;
this.F=b;this.B=new g.nD;this.A=new g7(this.GX,this);this.o=this.fb=null;this.K=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.M=c||!1},AEa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Uq,sessionId:a.o.B,arrayId:a.o.nk}},BEa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&uEa(a.o),qEa(a.o));a.H=0},i7=function(a){return!!a.o&&3==a.o.o},CEa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},j7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||window.document.location.href;var b=g.Tg(a)||"";b&&(this.port=":"+b);this.domain=g.Sg(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Cb(a,"10.0")&&(this.A=!1))},k7=function(a,b){var c=a.o;
if(g.u(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.dh(c+b,{})},l7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Fa(a.C,d,!0),onError:g.Fa(a.B,e),Bd:g.Fa(a.D,e)};c&&(a.Pb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.EE(b,a)},GEa=function(){var a=DEa;
EEa();m7.push(a);FEa(m7)},n7=function(a,b){EEa();
var c=m7,d=HEa(a,String(b));g.Qa(c)?IEa(d):(FEa(c),(0,g.C)(c,function(a){a(d)}))},EEa=function(){m7||(m7=g.y("yt.mdx.remote.debug.handlers_")||[],g.ua("yt.mdx.remote.debug.handlers_",m7,void 0))},IEa=function(a){var b=(o7+1)%50;
o7=b;p7[b]=a;q7||(q7=49==b)},FEa=function(a){var b=p7;
if(b[0]){var c=o7,d=q7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
p7=Array(50);o7=-1;q7=!1}},HEa=function(a,b){var c=((0,g.G)()-JEa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},r7=function(a){g.YF.call(this);
this.G=a;this.o=[]},KEa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},LEa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Ud)(a.o,function(a){return!!u6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=KEa(a,b[d])||c;return c},MEa=function(a,b){var c=a.o.length;
a.o=(0,g.Ud)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},s7=function(a,b,c,d){g.YF.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Fa=window.NaN},u7=function(a){r7.call(this,"LocalScreenService");
this.B=a;this.A=window.NaN;t7(this);this.info("Initializing with "+s6(this.o))},NEa=function(a){if(a.o.length){var b=(0,g.I)(a.o,function(a){return a.id}),c=k7(a.B,"/pairing/get_lounge_token_batch");
l7(a.B,c,{screen_ids:b.join(",")},(0,g.A)(a.PK,a),(0,g.A)(a.OK,a))}},t7=function(a){var b=FDa(LDa());
b=(0,g.Ud)(b,function(a){return!a.uuid});
return LEa(a,b)},v7=function(a,b){NDa((0,g.I)(a.o,DDa));
b&&MDa()},x7=function(a,b){g.YF.call(this);
this.F=b;var c=g.hH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Pa(c,l)}this.o=d;this.D=a;this.B=this.C=window.NaN;this.A=null;w7("Initialized with "+g.Kg(this.o))},OEa=function(a,b,c){var d=k7(a.D,"/pairing/get_screen_availability");
l7(a.D,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},y7=function(a,b){a:if(g.Qb(b)!=g.Qb(a.o))var c=!1;
else{c=g.Ub(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(w7("Updated online screens: "+g.Kg(a.o)),a.o=b,a.V("screenChange"));PEa(a)},z7=function(a){(0,window.isNaN)(a.B)||g.pE(a.B);
a.B=g.nE((0,g.A)(a.Jv,a),0<a.C&&a.C<(0,g.G)()?2E4:1E4)},w7=function(a){n7("OnlineScreenService",a)},QEa=function(a){var b={};
(0,g.C)(a.F(),function(a){a.token?b[a.token]=a.id:this.hc("Requesting availability of screen w/o lounge token.")});
return b},PEa=function(a){a=g.Ub(g.Nb(a.o,function(a){return a}));
g.gb(a);a.length?g.gH("yt-remote-online-screen-ids",a.join(","),60):g.iH("yt-remote-online-screen-ids")},A7=function(a){r7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};REa(this)},TEa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.te();if(k=(c?v6(k,c):null)||v6(k,b)){k.uuid=b;var l=B7(a,k);OEa(a.A,l,function(a){e(a?l:null)})}else c?SEa(a,c,(0,g.A)(function(a){var f=B7(this,new p6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));OEa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},UEa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},SEa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Pb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.EE(k7(a.F,"/pairing/get_lounge_token_batch"),e)},VEa=function(a){a.o=a.B.te();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+s6(a.o))},REa=function(a){C7(a);
a.B=new u7(a.F);a.B.subscribe("screenChange",(0,g.A)(a.eL,a));VEa(a);a.C=FDa(g.hH("yt-remote-automatic-screen-cache")||[]);C7(a);a.info("Initializing automatic screens: "+s6(a.C));a.A=new x7(a.F,(0,g.A)(a.te,a,!0));a.A.subscribe("screenChange",(0,g.A)(function(){this.V("onlineScreenChange")},a))},B7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=v6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.gH("yt-remote-automatic-screen-cache",(0,g.I)(a.C,DDa)));C7(a);a.D[b.uuid]=b.id;g.gH("yt-remote-device-id-map",a.D,31536E3);return b},C7=function(a){a.D=g.hH("yt-remote-device-id-map")||{}},D7=function(a,b,c){g.YF.call(this);
this.M=c;this.J=a;this.A=b;this.B=null},E7=function(a,b){n7(a.M,b)},F7=function(a,b){D7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.A)(this.MX,this);this.D=(0,g.A)(this.KV,this);this.C=g.nE((0,g.A)(function(){WEa(this,null)},this),12E4)},XEa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Kg(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.z,(0,g.A)(function(){E7(this,"Failed to send message: getMdxSessionStatus.")},a)):E7(a,"Sending yt message without session: "+g.Kg(b))},WEa=function(a,b){g.pE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.A)(a.Sp,a),d=(0,g.A)(a.ze,a);a.Gz(b,c,d,5)}}else a.ze(Error("Waiting for session status timed out."))},G7=function(a,b,c){D7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.O=c;this.D=null;this.G=g.z;this.F=window.NaN;this.L=(0,g.A)(this.PX,this);this.o=g.z},YEa=function(a){a.o=a.J.ZF(a.K,a.A.label,a.A.friendlyName,(0,g.A)(function(a){this.o=g.z;
this.Sp(a)},a),(0,g.A)(function(a){this.o=g.z;
this.ze(a)},a))},ZEa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.O;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}PDa()&&(b.env_useStageMdx=1);return g.bh(b)},H7=function(a,b){D7.call(this,a,b,"ManualSession");
this.o=g.nE((0,g.A)(this.qk,this,null),150)},I7=function(a,b,c,d){g.YF.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.A)(this.lU,this)},$Ea=function(a,b){return b?g.La(a.B,function(a){return q6(b,a.label)},a):null},J7=function(a){n7("Controller",a)},DEa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},K7=function(a){return a.D||!!a.B.length||!!a.o},L7=function(a,b,c){b!=a.o&&(g.lf(a.o),(a.o=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.A):a.V("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.A)(a.GD,a,b)),b.B?a.V("yt-remote-cast2-session-change",b.B):c&&a.o.qk(null)):a.V("yt-remote-cast2-session-change",null))},aFa=function(a){var b=a.A.YF(),c=a.o&&a.o.A;
a=(0,g.I)(b,function(a){c&&q6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=$Ea(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},gFa=function(a,b,c,d,e,f,k){bFa()?cFa(b,e,f,k)&&(N7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?dFa(a,c):(window.__onGCastApiAvailable=function(b,d){b?dFa(a,c):(O7("Failed to load cast API: "+d),P7(!1),N7(!1),g.iH("yt-remote-cast-available"),g.iH("yt-remote-cast-receiver"),eFa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):SDa():G6("CriOS")?XDa():G6("Android")&&G6("Chrome/")&&window.navigator.presentation?YDa():window.chrome&&window.navigator.presentation&&!G6("Edge")?(H6(),D6(fFa.map(VDa))):E6())):M7("Cannot initialize because not running Chrome")},eFa=function(){M7("dispose");
var a=Q7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);hFa(!1);g.kG(R7);R7.length=0},S7=function(){return!!g.hH("yt-remote-cast-installed")},iFa=function(){var a=g.hH("yt-remote-cast-receiver");
return a?a.friendlyName:null},jFa=function(){M7("clearCurrentReceiver");
g.iH("yt-remote-cast-receiver")},kFa=function(){return S7()?Q7()?Q7().getCastSession():(O7("getCastSelector: Cast is not initialized."),null):(O7("getCastSelector: Cast API is not installed!"),null)},U7=function(){S7()?Q7()?T7()?(M7("Requesting cast selector."),Q7().requestSession()):(M7("Wait for cast API to be ready to request the session."),R7.push(g.jG("yt-remote-cast2-api-ready",U7))):O7("requestCastSelector: Cast is not initialized."):O7("requestCastSelector: Cast API is not installed!")},V7=
function(a,b){T7()?Q7().setConnectedScreenStatus(a,b):O7("setConnectedScreenStatus called before ready.")},bFa=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.GJ||a},lFa=function(a,b){Q7().init(a,b)},cFa=function(a,b,c,d){var e=!1;
Q7()||(a=new I7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.gH("yt-remote-cast-available",a);g.nG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){M7("onReceiverSelected: "+a.friendlyName);
g.gH("yt-remote-cast-receiver",a);g.nG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){M7("onReceiverResumed: "+a.friendlyName);
g.gH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){M7("onSessionChange: "+r6(a));
a||g.iH("yt-remote-cast-receiver");g.nG("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
M7("cloudview.createSingleton_: "+e);return e},Q7=function(){return g.y("yt.mdx.remote.cloudview.instance_")},dFa=function(a,b){P7(!0);
N7(!1);lFa(a,function(a){a?(hFa(!0),g.mG("yt-remote-cast2-api-ready")):(O7("Failed to initialize cast API."),P7(!1),g.iH("yt-remote-cast-available"),g.iH("yt-remote-cast-receiver"),eFa());b(a)})},M7=function(a){n7("cloudview",a)},O7=function(a){n7("cloudview",a)},P7=function(a){M7("setCastInstalled_ "+a);
g.gH("yt-remote-cast-installed",a)},T7=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},hFa=function(a){M7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},N7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},W7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.o=-1;this.muted=!1;this.audioTrackId=null;this.G=this.H=0;this.A=null;this.hasNext=this.ag=!1;this.K=this.J=this.B=this.D=0;this.C=window.NaN;this.F=!1;this.reset(a)},X7=function(a){a.audioTrackId=null;
a.A=null;a.o=-1;a.ag=!1;a.hasNext=!1;a.H=0;a.G=(0,g.G)();a.D=0;a.B=0;a.J=0;a.K=0;a.C=window.NaN;a.F=!1},Y7=function(a){return a.qb()?((0,g.G)()-a.G)/1E3:0},Z7=function(a,b){a.H=b;
a.G=(0,g.G)()},$7=function(a){switch(a.o){case 1:case 1081:return((0,g.G)()-a.G)/1E3+a.H;
case -1E3:return 0}return a.H},a8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&X7(a)},b8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.o;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.gc(a.A);b.hasPrevious=a.ag;b.hasNext=a.hasNext;b.playerTime=a.H;b.playerTimeAt=a.G;b.seekableStart=a.D;b.seekableEnd=a.B;b.duration=a.J;b.loadedTime=a.K;b.liveIngestionTime=a.C;return b},d8=function(a,b){g.YF.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.EC;this.B=this.A=null;this.J=(0,g.A)(this.ER,this);this.G=(0,g.A)(this.Jm,this);this.H=(0,g.A)(this.DR,this);this.K=(0,g.A)(this.QR,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Fw,this),mFa(this))):c=3;0!=c&&(b?this.Fw(c):g.nE((0,g.A)(function(){this.Fw(c)},this),0));
var d=kFa();d&&c8(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},e8=function(a){return new W7(a.C.getPlayerContextData())},mFa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.Fa(this.gU,a),this))},a)},nFa=function(a){(0,g.C)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},f8=function(a,b){50>a.D.xc()&&g.GC(a.D,b)},h8=function(a,b,c){var d=e8(a);
Z7(d,c);-1E3!=d.o&&(d.o=b);g8(a,d)},i8=function(a,b,c){a.C.sendMessage(b,c)},g8=function(a,b){nFa(a);
a.C.setPlayerContextData(b8(b));mFa(a)},c8=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.Jm(null));
a.B=b;a.B&&(n7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.Jm(a.B.media[0]))},oFa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=e8(a);b.contentId!=d.videoId&&n7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.o=c.playerState;Z7(d,a.A.getEstimatedTime());g8(a,d)}else n7("CP","No cast media video. Ignoring state update.")},j8=function(a,b,c){return(0,g.A)(function(a){this.hc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.hc("Retrying "+b+" using MDx browser channel."),i8(this,b,c))},a)},k8=function(a,b,c){g.YF.call(this);
this.D=window.NaN;this.O=!1;this.K=this.J=this.L=this.M=window.NaN;this.T=[];this.C=this.G=this.B=this.gb=this.o=null;this.sa=a;this.T.push(g.HF(window,"beforeunload",(0,g.A)(this.GK,this)));this.A=[];this.gb=new W7;this.ba=b.id;this.o=pFa(this,c);this.o.subscribe("handlerOpened",this.IR,this);this.o.subscribe("handlerClosed",this.FR,this);this.o.subscribe("handlerError",this.GR,this);this.o.subscribe("handlerMessage",this.HR,this);CEa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.gb.videoId;g.jH()&&g.gH("yt-remote-session-video-id",a)},this)},l8=function(a){n7("conn",a)},pFa=function(a,b){return new h7(k7(a.sa,"/bc"),b)},m8=function(a,b){a.V("proxyStateChange",b)},qFa=function(a){a.D=g.nE((0,g.A)(function(){l8("Connecting timeout");
this.F(1)},a),2E4)},n8=function(a){g.pE(a.D);
a.D=window.NaN},o8=function(a){g.pE(a.M);
a.M=window.NaN},rFa=function(a){p8(a);
a.L=g.nE((0,g.A)(function(){q8(this,"getNowPlaying")},a),2E4)},p8=function(a){g.pE(a.L);
a.L=window.NaN},tFa=function(a,b){b&&(n8(a),o8(a));
b==(i7(a.o)&&(0,window.isNaN)(a.D))?b&&(m8(a,1),q8(a,"getSubtitlesTrack")):b?(a.Z()&&a.gb.reset(),m8(a,1),q8(a,"getNowPlaying"),sFa(a)):a.F(1)},uFa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.gb.videoId&&(g.$b(b.params)?a.gb.A=null:a.gb.A=b.params,a.V("remotePlayerChange"))},vFa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.gb.listId=b.params.listId||a.gb.listId;a8(a.gb,c,d);a.V("remoteQueueChange")},xFa=function(a,b){b.params=b.params||{};
vFa(a,b);wFa(a,b);a.V("autoplayDismissed")},wFa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
Z7(a.gb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.gb.o&&(c=-1E3);a.gb.o=c;c=Number(b.params.loadedTime);a.gb.K=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.gb.J=(0,window.isNaN)(c)?0:c;c=a.gb;var d=Number(b.params.liveIngestionTime);c.C=d;c.F=(0,window.isNaN)(d)?!1:!0;c=a.gb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.D=(0,window.isNaN)(d)?0:d;c.B=(0,window.isNaN)(e)?0:e;1==a.gb.o?rFa(a):p8(a);
a.V("remotePlayerChange")},yFa=function(a,b){if(-1E3!=a.gb.o){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.gb.o=c;c=(0,window.parseInt)(b.params.currentTime,10);Z7(a.gb,(0,window.isNaN)(c)?0:c);a.V("remotePlayerChange")}},zFa=function(a,b){var c="true"==b.params.muted;
a.gb.volume=(0,window.parseInt)(b.params.volume,10);a.gb.muted=c;a.V("remotePlayerChange")},AFa=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},BFa=function(a,b){var c="true"==b.params.hasNext;
a.gb.ag="true"==b.params.hasPrevious;a.gb.hasNext=c;a.V("previousNextChange")},sFa=function(a){g.pE(a.K);
a.K=g.nE((0,g.A)(a.F,a,1),864E5)},q8=function(a,b,c){c?l8("Sending: action="+b+", params="+g.Kg(c)):l8("Sending: action="+b);
a.o.sendMessage(b,c)},r8=function(a){r7.call(this,"ScreenServiceProxy");
this.hd=a;this.A=[];this.A.push(this.hd.$_s("screenChange",(0,g.A)(this.KX,this)));this.A.push(this.hd.$_s("onlineScreenChange",(0,g.A)(this.FT,this)))},GFa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.hE("MDX_CONFIG")||b;HDa();z6();s8||(s8=new j7(b?b.loungeApiHost:void 0),PDa()&&(s8.o="/api/loungedev"));t8||(t8=g.y("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",t8,void 0));CFa();var c=u8();if(!c){var d=new A7(s8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=u8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);gFa(a,d,function(a){a?v8()&&V7(v8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.nG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),w8("Initializing: "+g.Kg(b)),x8.push(g.jG("yt-remote-cast2-availability-change",function(){g.nG("yt-remote-receiver-availability-change")})),x8.push(g.jG("yt-remote-cast2-receiver-selected",function(){y8(null);
g.nG("yt-remote-auto-connect","cast-selector-receiver")})),x8.push(g.jG("yt-remote-cast2-receiver-resumed",function(){g.nG("yt-remote-receiver-resumed","cast-selector-receiver")})),x8.push(g.jG("yt-remote-cast2-session-change",DFa)),x8.push(g.jG("yt-remote-connection-change",function(a){a?V7(v8(),"YouTube TV"):z8()||(V7(null,null),jFa())})),a=A8(),b.isAuto&&(a.id+="#dial"),g.dG("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),w8(" -- with channel params: "+
g.Kg(a)),EFa(a),c.start(),v8()||FFa())},IFa=function(){var a=HFa();
S7()&&g.hH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},HFa=function(){var a=u8().hd.$_gos();
var b=B8();b&&C8()&&(u6(a,b)||a.push(b));return GDa(a)},D8=function(){var a=JFa();
!a&&S7()&&iFa()&&(a={key:"cast-selector-receiver",name:iFa()});return a},JFa=function(){var a=HFa(),b=B8();
b||(b=z8());return g.La(a,function(a){return b&&q6(b,a.key)?!0:!1})},B8=function(){var a=v8();
if(!a)return null;var b=u8().te();return v6(b,a)},DFa=function(a){w8("remote.onCastSessionChange_: "+r6(a));
if(a){var b=B8();b&&b.id==a.id?V7(b.id,"YouTube TV"):(b&&E8(),F8(a,1))}else C8()&&E8()},E8=function(){T7()?Q7().stopSession():O7("stopSession called before API ready.");
var a=C8();a&&(a.disconnect(1),G8(null))},H8=function(){var a=C8();
return!!a&&3!=a.getProxyState()},w8=function(a){n7("remote",a)},u8=function(){if(!I8){var a=g.y("yt.mdx.remote.screenService_");
I8=a?new r8(a):null}return I8},v8=function(){return g.y("yt.mdx.remote.currentScreenId_")},KFa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},LFa=function(){return g.y("yt.mdx.remote.connectData_")},y8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},C8=function(){return g.y("yt.mdx.remote.connection_")},G8=function(a){var b=C8();
y8(null);a||KFa("");g.ua("yt.mdx.remote.connection_",a,void 0);t8&&((0,g.C)(t8,function(b){b(a)}),t8.length=0);
b&&!a?g.nG("yt-remote-connection-change",!1):!b&&a&&g.nG("yt-remote-connection-change",!0)},z8=function(){var a=g.jH();
if(!a)return null;var b=u8().te();return v6(b,a)},F8=function(a,b){B8()&&B8();
KFa(a.id);var c=new k8(s8,a,A8());c.connect(b,LFa());c.subscribe("beforeDisconnect",function(a){g.nG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){C8()&&G8(null)});
G8(c)},FFa=function(){var a=z8();
a?(w8("Resume connection to: "+r6(a)),F8(a,0)):(A6(),jFa(),w8("Skipping connecting because no session screen found."))},CFa=function(){var a=A8();
if(g.$b(a)){a=y6();var b=g.hH("yt-remote-session-name")||"",c=g.hH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},A8=function(){return g.y("yt.mdx.remote.channelParams_")||{}},EFa=function(a){a?(g.gH("yt-remote-session-app",a.app),g.gH("yt-remote-session-name",a.name)):(g.iH("yt-remote-session-app"),g.iH("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},J8=function(a,b,c){g.M.call(this);
this.H=a;this.A=b;this.B=new g.VF(this);g.N(this,this.B);this.B.R(b,"onCaptionsTrackListChanged",this.YS);this.B.R(b,"captionschanged",this.CR);this.B.R(b,"captionssettingschanged",this.mF);this.B.R(b,"videoplayerreset",this.Tp);this.B.R(b,"mdxautoplaycancel",this.FJ);this.T=this.B.R(b,"onVolumeChange",this.pD);this.G=!1;this.o=c;c.subscribe("proxyStateChange",this.CD,this);c.subscribe("remotePlayerChange",this.Mm,this);c.subscribe("remoteQueueChange",this.Tp,this);c.subscribe("autoplayUpNext",this.aD,
this);c.subscribe("previousNextChange",this.zD,this);c.subscribe("nowAutoplaying",this.rD,this);c.subscribe("autoplayDismissed",this.ZC,this);this.suggestion=null;this.J=new g.kQ(64);this.C=new g.ou(this.iF,500,this);g.N(this,this.C);this.D=new g.ou(this.jF,1E3,this);g.N(this,this.D);this.L=new I6(this.lX,0,this);g.N(this,this.L);this.F={};this.M=new g.ou(this.IF,1E3,this);g.N(this,this.M);this.K=new g.il(this.BP,1E3,this);g.N(this,this.K);this.O=g.z;this.mF();this.Tp();this.Mm()},K8=function(a,b){var c=
a.H,d=a.A.getVideoData().lengthSeconds;
c.J=b||0;c.o.V("progresssync",b,d)},MFa=function(a){K8(a,0);
a.C.stop();L8(a,new g.kQ(64))},N8=function(a,b){if(M8(a)&&!a.G){var c=null;
b&&(c={style:a.A.Yi()},g.ic(c,b));a.o.WE(a.A.getVideoData(1).videoId,c);a.F=e8(a.o).A}},O8=function(a,b){var c=a.A.jg();
if(c){var d=c.re();var e=c.listId.toString()}var f=a.A.getVideoData(1);c=a.o;var k=f.videoId,l=d;d=f.playerParams;var m=f.ik;f=wDa(f);var n=e8(c);l=l||0;var p={videoId:k,currentIndex:l};a8(n,k,l);g.u(b)&&(Z7(n,b),p.currentTime=b);g.u(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.Kg(f));i8(c,"setPlaylist",p);e||g8(c,n);L8(a,new g.kQ(1))},NFa=function(a,b){if(b){var c=a.A.Ac("captions","tracklist",{zA:1});
c&&c.length?(a.A.Td("captions","track",b),a.G=!1):(a.A.zk("captions"),a.G=!0)}else a.A.Td("captions","track",{})},M8=function(a){return e8(a.o).videoId==a.A.getVideoData(1).videoId},L8=function(a,b){a.D.stop();
var c=a.J;if(!g.pQ(c,b)){var d=g.X(b,2);d!=g.X(a.J,2)&&g.jU(a.A,d);a.J=b;OFa(a.H,c,b)}},P8=function(a){g.W.call(this,{I:"div",
N:"ytp-remote",P:[{I:"div",N:"ytp-remote-display-status",P:[{I:"div",N:"ytp-remote-display-status-icon",P:[g.mra()]},{I:"div",N:"ytp-remote-display-status-text",ca:"{{statustext}}"}]}]});this.A=new g.$U(this,250);g.N(this,this.A);this.C=a;this.R(a,"presentingplayerstatechange",this.D);PFa(this,g.gU(a))},PFa=function(a,b){if(3==a.C.Ra()){var c={RECEIVER_NAME:a.C.Ac("remote","currentReceiver").name};
c=g.X(b,128)?g.f0("Error on $RECEIVER_NAME",c):b.qb()||g.X(b,4)?g.f0("Playing on $RECEIVER_NAME",c):g.f0("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.A.show()}else a.A.hide()},Q8=function(a,b){g.kZ.call(this,"Play on",0,a,b);
this.A=a;this.J={};this.R(a,"onMdxReceiversChange",this.L);this.R(a,"presentingplayerstatechange",this.L);this.L()},R8=function(a){g.GU.call(this,a);
this.B={key:t6(),name:"This computer"};this.D=null;this.F=[];this.K=this.A=null;this.H=[this.B];this.C=this.B;this.G=new g.kQ(64);this.J=0;if(!g.GN(g.Y(this.o))){a=this.o;var b=g.ZH(a);b&&(b=b.qp())&&(b=new Q8(a,b),g.N(this,b));b=new P8(a);g.N(this,b);g.zU(a,b.element,4)}},OFa=function(a,b,c){a.G=c;
a.o.V("presentingplayerstatechange",new g.uQ(c,b))},S8=function(a,b){if(b.key!=a.C.key)if(b.key==a.B.key)E8();
else{a.C=b;var c=a.o.getPlaylistId();var d=a.o.getVideoData(1);var e=d.videoId;if(c||e){var f=a.o.jg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.ac(l).videoId}else k=[e];f=a.o.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.ik,index:Math.max(a.o.DB(),0),currentTime:0==f?void 0:f};(d=wDa(d))&&(c.locationInfo=d);d=c}else d=null;w8("Connecting to: "+g.Kg(b));"cast-selector-receiver"==b.key?(y8(d||null),T7()?Q7().setLaunchParams(d||null):
O7("setLaunchParams called before ready.")):!d&&H8()&&v8()==b.key?g.nG("yt-remote-connection-change",!0):(E8(),y8(d||null),d=u8().te(),(d=v6(d,b.key))&&F8(d,1))}},dEa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},S6={"'":"\\'"},QFa={},CDa={aZ:"atp",F3:"ska",U2:"que",d2:"mus",B3:"sus",j0:"dsp"};
o6.prototype.fo=function(){var a=new o6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var B6,x6="",F6=C6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",WDa=C6("loadCastFramework")||C6("loadCastApplicationFramework"),fFa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(I6,g.M);g.h=I6.prototype;g.h.BK=function(a){this.C=arguments;this.o=!1;this.Fa?this.B=(0,g.G)()+this.wd:this.Fa=g.Eg(this.D,this.wd)};
g.h.stop=function(){this.Fa&&(g.Fg(this.Fa),this.Fa=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.X=function(){this.stop();I6.ea.X.call(this)};
g.h.CK=function(){this.B?(this.Fa=g.Eg(this.D,this.B-(0,g.G)()),this.B=null):(this.Fa=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};J6.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
J6.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=K6.prototype;g.h.Ei=null;g.h.Hf=!1;g.h.ll=null;g.h.yw=null;g.h.Qk=null;g.h.Zj=null;g.h.zh=null;g.h.bi=null;g.h.fj=null;g.h.Rc=null;g.h.kn=0;g.h.If=null;g.h.Vq=null;g.h.Ah=null;g.h.Vl=-1;g.h.CE=!0;g.h.pi=!1;g.h.Ps=0;g.h.gq=null;var bEa={},N6={};g.h=K6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.bW=function(a){a=a.target;var b=this.gq;b&&3==g.zx(a)?b.Xj():this.SF(a)};
g.h.SF=function(a){try{if(a==this.Rc)a:{var b=g.zx(this.Rc),c=this.Rc.A,d=this.Rc.getStatus();if(g.Gd&&!g.vc(10)||g.Id&&!g.uc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.pf&&!g.Dx(this.Rc))break a;this.pi||4!=b||7==c||(8==c||0>=d?this.o.Bf(3):this.o.Bf(2));U6(this);var e=this.Rc.getStatus();this.Vl=e;var f=g.Dx(this.Rc);(this.Hf=200==e)?(4==b&&Q6(this),this.D?(cEa(this,b,f),g.pf&&this.Hf&&3==b&&(this.Y.W(this.A,"tick",this.XV),this.A.start())):P6(this,f),this.Hf&&!this.pi&&(4==b?this.o.Rp(this):
(this.Hf=!1,M6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Ah=3,O6(13)):(this.Ah=0,O6(14)),Q6(this),R6(this))}}catch(k){this.Rc&&g.Dx(this.Rc)}finally{}};
g.h.XV=function(){var a=g.zx(this.Rc),b=g.Dx(this.Rc);this.kn<b.length&&(U6(this),cEa(this,a,b),this.Hf&&4!=a&&M6(this))};
g.h.hV=function(a){T6((0,g.A)(this.gV,this,a),0)};
g.h.gV=function(a){this.pi||(U6(this),P6(this,a),M6(this))};
g.h.LD=function(a){T6((0,g.A)(this.fV,this,a),0)};
g.h.fV=function(a){this.pi||(Q6(this),this.Hf=a,this.o.Rp(this),this.o.Bf(4))};
g.h.cancel=function(){this.pi=!0;Q6(this)};
g.h.xV=function(){this.ll=null;var a=(0,g.G)();0<=a-this.yw?(2!=this.Zj&&this.o.Bf(3),Q6(this),this.Ah=2,O6(18),R6(this)):fEa(this,this.yw-a)};g.h=iEa.prototype;g.h.Ns=null;g.h.Be=null;g.h.hq=!1;g.h.Qz=null;g.h.to=null;g.h.Ut=null;g.h.Os=null;g.h.Ue=null;g.h.Lg=-1;g.h.Ul=null;g.h.ul=null;g.h.connect=function(a){this.Os=a;a=W6(this.o,null,this.Os);O6(3);this.Qz=(0,g.G)();var b=this.o.H;null!=b?(this.Ul=b[0],(this.ul=b[1])?(this.Ue=1,jEa(this)):(this.Ue=2,Y6(this))):(n6(a,"MODE","init"),this.Be=new K6(this,void 0,void 0,void 0),this.Be.Ei=this.Ns,L6(this.Be,a,!1,null,!0),this.Ue=0)};
g.h.GJ=function(a){if(a)this.Ue=2,Y6(this);else{O6(4);var b=this.o;b.Wf=b.nh.Lg;e7(b,9)}a&&this.Bf(2)};
g.h.Zr=function(a){return this.o.Zr(a)};
g.h.abort=function(){this.Be&&(this.Be.cancel(),this.Be=null);this.Lg=-1};
g.h.Pz=function(){return!1};
g.h.DD=function(a,b){this.Lg=a.Vl;if(0==this.Ue)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.Wf=this.Lg;e7(c,2);return}this.Ul=c[0];this.ul=c[1]}else c=this.o,c.Wf=this.Lg,e7(c,2);else if(2==this.Ue)if(this.hq)O6(7),this.Ut=(0,g.G)();else if("11111"==b){if(O6(6),this.hq=!0,this.to=(0,g.G)(),c=this.to-this.Qz,!g.Gd||g.vc(10)||500>c)this.Lg=200,this.Be.cancel(),O6(12),X6(this.o,this,!0)}else O6(8),this.to=this.Ut=(0,g.G)(),this.hq=!1};
g.h.Rp=function(){this.Lg=this.Be.Vl;if(this.Be.Hf)0==this.Ue?this.ul?(this.Ue=1,jEa(this)):(this.Ue=2,Y6(this)):2==this.Ue&&((!g.Gd||g.vc(10)?!this.hq:200>this.Ut-this.to)?(O6(11),X6(this.o,this,!1)):(O6(12),X6(this.o,this,!0)));else{0==this.Ue?O6(9):2==this.Ue&&O6(10);var a=this.o;a.Wf=this.Lg;e7(a,2)}};
g.h.Xm=function(){return this.o.Xm()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Bf=function(a){this.o.Bf(a)};g.h=Z6.prototype;g.h.Gl=null;g.h.fe=null;g.h.wc=null;g.h.Ms=null;g.h.xo=null;g.h.ey=null;g.h.Ko=null;g.h.Gm=0;g.h.UQ=0;g.h.ud=null;g.h.rh=null;g.h.zg=null;g.h.ti=null;g.h.nh=null;g.h.Uq=null;g.h.nk=-1;g.h.OA=-1;g.h.Wf=-1;g.h.Nj=0;g.h.Bj=0;g.h.si=8;var f7=new g.Qf;g.B(lEa,g.nf);g.B(mEa,g.nf);g.B(nEa,g.nf);g.h=Z6.prototype;g.h.connect=function(a,b,c,d,e){O6(0);this.Ms=b;this.Gl=c||{};d&&g.u(e)&&(this.Gl.OSID=d,this.Gl.OAID=e);this.F?(T6((0,g.A)(this.Dy,this,a),100),rEa(this)):this.Dy(a)};
g.h.Dy=function(a){this.nh=new iEa(this);this.nh.Ns=null;this.nh.A=this.D;this.nh.connect(a)};
g.h.Pz=function(){return 0==this.o};
g.h.JD=function(a){this.rh=null;uEa(this,a)};
g.h.ID=function(){this.zg=null;this.wc=new K6(this,this.B,"rpc",this.G);this.wc.Ei=null;this.wc.Ps=0;var a=this.ey.clone();g.Rm(a,"RID","rpc");g.Rm(a,"SID",this.B);g.Rm(a,"CI",this.Uq?"0":"1");g.Rm(a,"AID",this.nk);$6(this,a);if(!g.Gd||g.vc(10))g.Rm(a,"TYPE","xmlhttp"),L6(this.wc,a,!0,this.Ko,!1);else{g.Rm(a,"TYPE","html");var b=this.wc,c=!!this.Ko;b.Zj=3;b.zh=m6(a.clone());eEa(b,c)}};
g.h.DD=function(a,b){if(0!=this.o&&(this.wc==a||this.fe==a))if(this.Wf=a.Vl,this.fe==a&&3==this.o)if(7<this.si){try{var c=this.D.parse(b)}catch(f){c=null}if(g.za(c)&&3==c.length)if(0==c[0])a:{if(!this.zg){if(this.wc)if(this.wc.Qk+3E3<this.fe.Qk)b7(this),this.wc.cancel(),this.wc=null;else break a;d7(this);O6(19)}}else this.OA=c[1],0<this.OA-this.nk&&37500>c[2]&&this.Uq&&0==this.Bj&&!this.ti&&(this.ti=T6((0,g.A)(this.wR,this),6E3));else e7(this,11)}else b!=QFa.d_.o&&e7(this,11);else if(this.wc==a&&
b7(this),!g.E(b)){c=this.D.parse(b);g.za(c);for(var d=0;d<c.length;d++){var e=c[d];this.nk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.Ko=e[2],e=e[3],null!=e?this.si=e:this.si=6,this.o=3,this.ud&&this.ud.ty(),this.ey=W6(this,this.Xm()?this.Ko:null,this.Ms),vEa(this)):"stop"==e[0]&&e7(this,7):3==this.o&&("stop"==e[0]?e7(this,7):"noop"!=e[0]&&this.ud&&this.ud.ry(e),this.Bj=0)}}};
g.h.wR=function(){null!=this.ti&&(this.ti=null,this.wc.cancel(),this.wc=null,d7(this),O6(20))};
g.h.Rp=function(a){if(this.wc==a){b7(this);this.wc=null;var b=2}else if(this.fe==a)this.fe=null,b=1;else return;this.Wf=a.Vl;if(0!=this.o)if(a.Hf)1==b?(b=(0,g.G)()-a.Qk,f7.dispatchEvent(new mEa(f7,a.fj?a.fj.length:0,b,this.Nj)),a7(this),this.C.length=0):vEa(this);else{var c=a.Ah,d;if(!(d=3==c||7==c||0==c&&0<this.Wf)){if(d=1==b)this.fe||this.rh||1==this.o||2<=this.Nj?d=!1:(this.rh=T6((0,g.A)(this.JD,this,a),wEa(this,this.Nj)),this.Nj++,d=!0);d=!(d||2==b&&d7(this))}if(d)switch(c){case 1:e7(this,5);
break;case 4:e7(this,10);break;case 3:e7(this,6);break;case 7:e7(this,12);break;default:e7(this,2)}}};
g.h.cK=function(a){if(!g.Pa(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.WW=function(a){a?O6(2):(O6(1),xEa(this,8))};
g.h.Zr=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.tx;a.H=!1;return a};
g.h.isActive=function(){return!!this.ud&&this.ud.isActive(this)};
g.h.Bf=function(a){f7.dispatchEvent(new nEa(f7,a))};
g.h.Xm=function(){return!(!g.Gd||g.vc(10))};
g.h=yEa.prototype;g.h.ty=function(){};
g.h.ry=function(){};
g.h.qy=function(){};
g.h.Nr=function(){};
g.h.wz=function(){return{}};
g.h.isActive=function(){return!0};g.B(g7,g.M);g.h=g7.prototype;g.h.YU=function(){this.wd=Math.min(3E5,2*this.wd);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.wd+15E3*Math.random();g.pu(this.o,a);this.A=(0,g.G)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.wd=5E3};g.B(h7,yEa);g.h=h7.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.Yd=function(a){return this.B.Yd(a)};
g.h.V=function(a,b){return this.B.V.apply(this.B,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.lf(this.B),BEa(this),g.lf(this.A),this.A=null)};
g.h.ma=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new Z6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.o;e&&(e.ud=null);d.ud=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.nk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ic(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):i7(this)&&sEa(this.o,c)};
g.h.ty=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)sEa(this.o,a[b])}this.V("handlerOpened")};
g.h.qy=function(a){var b=2==a&&401==this.o.Wf;4==a||b||this.A.start();this.V("handlerError",a)};
g.h.Nr=function(a){if(!this.A.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.wz=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.ic(a,this.D);return a};
g.h.ry=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),qEa(this.o)):this.V("handlerMessage",new zEa(a[0],a[1]))};
g.h.GX=function(){this.A.isActive();var a=this.o,b=0;a.wc&&b++;a.fe&&b++;0!=b||this.connect(this.D,this.C)};j7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
j7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
j7.prototype.D=function(a){a(Error("request timed out"))};var JEa=(0,g.G)(),m7=null,p7=Array(50),o7=-1,q7=!1;g.B(r7,g.YF);r7.prototype.te=function(){return this.o};
r7.prototype.contains=function(a){return!!u6(this.o,a)};
r7.prototype.get=function(a){return a?v6(this.o,a):null};
r7.prototype.info=function(a){n7(this.G,a)};g.B(s7,g.YF);var RFa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=s7.prototype;g.h.start=function(){!this.o&&(0,window.isNaN)(this.Fa)&&this.XF()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);(0,window.isNaN)(this.Fa)||(g.pE(this.Fa),this.Fa=window.NaN)};
g.h.X=function(){this.stop();s7.ea.X.call(this)};
g.h.XF=function(){this.Fa=window.NaN;this.o=g.EE(k7(this.F,"/pairing/get_screen"),{method:"POST",Pb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.A)(this.IX,this),onError:(0,g.A)(this.HX,this),Bd:(0,g.A)(this.JX,this)})};
g.h.IX=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new p6(c))};
g.h.HX=function(a){this.o=null;a.status&&404==a.status?this.A>=RFa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=RFa[this.A],this.Fa=g.nE((0,g.A)(this.XF,this),a),this.A++):this.V("pairingFailed",Error("Server error "+a.status))};
g.h.JX=function(){this.o=null;this.V("pairingFailed",Error("Server not responding"))};g.B(u7,r7);g.h=u7.prototype;g.h.start=function(){t7(this)&&this.V("screenChange");!g.hH("yt-remote-lounge-token-expiration")&&NEa(this);g.pE(this.A);this.A=g.nE((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){t7(this);KEa(this,a);v7(this,!1);this.V("screenChange");b(a);a.token||NEa(this)};
g.h.remove=function(a,b){var c=t7(this);MEa(this,a)&&(v7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.h.Oq=function(a,b,c,d){var e=t7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,v7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.h.X=function(){g.pE(this.A);u7.ea.X.call(this)};
g.h.PK=function(a){t7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}v7(this,!b);b&&n7(this.G,"Missed "+b+" lounge tokens.")};
g.h.OK=function(a){n7(this.G,"Requesting lounge tokens failed: "+a)};g.B(x7,g.YF);g.h=x7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.hH("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.G)()-144E5<a?0:a)?z7(this):(this.C=(0,g.G)()+3E5,g.gH("yt-remote-fast-check-period",this.C),this.Jv())};
g.h.isEmpty=function(){return g.$b(this.o)};
g.h.update=function(){w7("Updating availability on schedule.");var a=this.F(),b=g.Nb(this.o,function(b,d){return b&&!!v6(a,d)},this);
y7(this,b)};
g.h.X=function(){g.pE(this.B);this.B=window.NaN;this.A&&(this.A.abort(),this.A=null);x7.ea.X.call(this)};
g.h.Jv=function(){g.pE(this.B);this.B=window.NaN;this.A&&this.A.abort();var a=QEa(this);if(g.Qb(a)){var b=k7(this.D,"/pairing/get_screen_availability");this.A=l7(this.D,b,{lounge_token:g.Ub(a).join(",")},(0,g.A)(this.GU,this,a),(0,g.A)(this.FU,this))}else y7(this,{}),z7(this)};
g.h.GU=function(a,b){this.A=null;var c=g.Ub(QEa(this));if(g.ib(c,g.Ub(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;y7(this,d);z7(this)}else this.hc("Changing Screen set during request."),this.Jv()};
g.h.FU=function(a){this.hc("Screen availability failed: "+a);this.A=null;z7(this)};
g.h.hc=function(a){n7("OnlineScreenService",a)};g.B(A7,r7);g.h=A7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.V("screenChange"),this.A.isEmpty()||this.V("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.Oq=function(a,b,c,d){this.B.contains(a)?this.B.Oq(a,b,c,d):(a="Updating name of unknown screen: "+a.name,n7(this.G,a),d(Error(a)))};
g.h.te=function(a){return a?this.o:g.Wa(this.o,(0,g.Ud)(this.C,function(a){return!this.contains(a)},this))};
g.h.YF=function(){return(0,g.Ud)(this.te(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.ZF=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new s7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.lf(f);d(B7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.lf(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.LX=function(a,b,c,d){g.EE(k7(this.F,"/pairing/get_screen"),{method:"POST",Pb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(a,d){var e=new p6(d.screen||{});if(!e.name||UEa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);UEa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(B7(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
Bd:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.lf(this.B);g.lf(this.A);A7.ea.X.call(this)};
g.h.eL=function(){VEa(this);this.V("screenChange");this.A.update()};
A7.prototype.dispose=A7.prototype.dispose;g.B(D7,g.YF);g.h=D7.prototype;g.h.Sp=function(a){this.B=a;this.V("sessionScreen",this.B)};
g.h.ze=function(a){this.ma()||(a&&E7(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.h.info=function(a){n7(this.M,a)};
g.h.bG=function(){return null};
g.h.Pv=function(a){var b=this.A;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){E7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.Pv("");D7.ea.X.call(this)};g.B(F7,D7);g.h=F7.prototype;g.h.Ov=function(a){if(this.o){if(this.o==a)return;E7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);XEa(this)};
g.h.qk=function(a){this.info("launchWithParams no-op for Cast: "+g.Kg(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.A)(function(){this.ze()},this),(0,g.A)(function(){this.ze(Error("Failed to stop receiver app."))},this)):this.ze(Error("Stopping cast device witout session."))};
g.h.Pv=g.z;g.h.X=function(){this.info("disposeInternal");g.pE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;F7.ea.X.call(this)};
g.h.KV=function(a,b){if(!this.ma())if(b){var c=g.nx(b);if(g.Ca(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Kg(c));switch(d){case "mdxSessionStatus":WEa(this,c.screenId);break;default:E7(this,"Unknown youtube message: "+d)}}else E7(this,"Unable to parse message.")}else E7(this,"No data in message.")};
g.h.Gz=function(a,b,c,d){TEa(this.J,this.A.label,a,this.A.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(E7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.nE((0,g.A)(this.Gz,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.bG=function(){return this.o};
g.h.MX=function(a){this.ma()||a||(E7(this,"Cast session died."),this.ze())};g.B(G7,D7);g.h=G7.prototype;g.h.Ov=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.qk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.z;g.pE(this.F);this.C?this.C.stop((0,g.A)(this.ze,this,null),(0,g.A)(this.ze,this,"Failed to stop DIAL device.")):this.ze()};
g.h.X=function(){this.o();this.o=g.z;g.pE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;G7.ea.X.call(this)};
g.h.PX=function(a){this.ma()||a||(E7(this,"DIAL session died."),this.o(),this.o=g.z,this.ze())};
g.h.It=function(a){this.K=t6();if(this.D){var b=new window.chrome.cast.DialLaunchResponse(!0,ZEa(this));a(b);YEa(this)}else this.G=(0,g.A)(function(){g.pE(this.F);this.G=g.z;this.F=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,ZEa(this));a(b);YEa(this)},this),this.F=g.nE((0,g.A)(function(){this.G()},this),100)};
g.h.tM=function(a,b,c){TEa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.A)(function(a){a&&a.token?(this.Sp(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.It(b,c)},this),(0,g.A)(function(a){E7(this,"Failed to get DIAL screen: "+a);
this.It(b,c)},this))};g.B(H7,D7);H7.prototype.stop=function(){this.ze()};
H7.prototype.Ov=g.z;H7.prototype.qk=function(){g.pE(this.o);this.o=window.NaN;var a=v6(this.J.te(),this.A.label);a?this.Sp(a):this.ze(Error("No such screen"))};
H7.prototype.X=function(){g.pE(this.o);this.o=window.NaN;H7.ea.X.call(this)};g.B(I7,g.YF);g.h=I7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.A)(this.FD,this),(0,g.A)(this.pU,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.hS,this);window.chrome.cast.initialize(c,
(0,g.A)(function(){this.ma()||(window.chrome.cast.addReceiverActionListener(this.C),GEa(),this.A.subscribe("onlineScreenChange",(0,g.A)(this.aG,this)),this.B=aFa(this),window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(a){this.hc("Failed to set initial custom receivers: "+g.Kg(a))},this)),this.V("yt-remote-cast2-availability-change",K7(this)),b(!0))},this),(0,g.A)(function(a){this.hc("Failed to initialize API: "+g.Kg(a));
b(!1)},this))};
g.h.DW=function(a,b){J7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)J7("Unsetting old screen status: "+this.o.A.friendlyName),L7(this,null)}if(a&&b){if(!this.o){c=v6(this.A.te(),a);if(!c){J7("setConnectedScreenStatus: Unknown screen.");return}var d=$Ea(this,c);d||(J7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.B.push(d),
window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(a){this.hc("Failed to set initial custom receivers: "+g.Kg(a))},this)));
J7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);L7(this,new H7(this.A,d),!0)}this.o.Pv(b)}else J7("setConnectedScreenStatus: no screen.")};
g.h.EW=function(a){this.ma()?this.hc("Setting connection data on disposed cast v2"):this.o?this.o.qk(a):this.hc("Setting connection data without a session")};
g.h.OX=function(){this.ma()?this.hc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),L7(this,null)):J7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.A)(this.FD,this),(0,g.A)(this.KU,this))};
g.h.X=function(){this.A.unsubscribe("onlineScreenChange",(0,g.A)(this.aG,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.C);g.Ua(g.y("yt.mdx.remote.debug.handlers_")||[],DEa);g.lf(this.o);I7.ea.X.call(this)};
g.h.hc=function(a){n7("Controller",a)};
g.h.GD=function(a,b){this.o==a&&(b||L7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.h.lU=function(a,b){if(!this.ma())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),J7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)J7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{J7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.V("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:L7(this,
new H7(this.A,a));break;case window.chrome.cast.ReceiverType.DIAL:L7(this,new G7(this.A,a,this.F));break;case window.chrome.cast.ReceiverType.CAST:L7(this,new F7(this.A,a));break;default:this.hc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.hc("Stopping receiver w/o session: "+a.friendlyName)}else this.hc("onReceiverAction_ called without receiver.")};
g.h.hS=function(a){if(this.ma())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.hc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.hc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.o.B)return J7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.o.B),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.hc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);L7(this,new G7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.A)(b.tM,b,(b.H.extraData||{}).screenId||null)):new window.Promise((0,g.A)(b.It,b))};
g.h.FD=function(a){if(!this.ma()){J7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)J7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),L7(this,new F7(this.A,b),!0);else{this.hc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=v6(this.A.te(),c.label);
d&&q6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(J7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.lf(this.o),this.o=new F7(this.A,b),this.o.subscribe("sessionScreen",(0,g.A)(this.GD,this,this.o)),this.o.qk(null));this.o.Ov(a)}}};
g.h.NX=function(){return this.o?this.o.bG():null};
g.h.KU=function(a){this.ma()||(this.hc("Failed to estabilish a session: "+g.Kg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&L7(this,null))};
g.h.pU=function(a){J7("Receiver availability updated: "+a);if(!this.ma()){var b=K7(this);this.D=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;K7(this)!=b&&this.V("yt-remote-cast2-availability-change",K7(this))}};
g.h.aG=function(){this.ma()||(this.B=aFa(this),J7("Updating custom receivers: "+g.Kg(this.B)),window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(){this.hc("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",K7(this)))};
I7.prototype.setLaunchParams=I7.prototype.EW;I7.prototype.setConnectedScreenStatus=I7.prototype.DW;I7.prototype.stopSession=I7.prototype.OX;I7.prototype.getCastSession=I7.prototype.NX;I7.prototype.requestSession=I7.prototype.requestSession;I7.prototype.init=I7.prototype.init;I7.prototype.dispose=I7.prototype.dispose;var R7=[];g.h=W7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";X7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.o=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.A=a.trackData,this.ag=a.hasPrevious,this.hasNext=a.hasNext,this.H=a.playerTime,this.G=a.playerTimeAt,this.D=a.seekableStart,this.B=a.seekableEnd,this.J=a.duration,this.K=a.loadedTime,this.C=a.liveIngestionTime,this.F=!(0,window.isNaN)(this.C))};
g.h.qb=function(){return 1==this.o};
g.h.isAdPlaying=function(){return 1081==this.o};
g.h.getDuration=function(){return this.F?this.J+Y7(this):this.J};
g.h.clone=function(){return new W7(b8(this))};g.B(d8,g.YF);g.h=d8.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.z,j8(this,"play")):i8(this,"play"),h8(this,1,$7(e8(this))),this.V("remotePlayerChange")):f8(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.z,j8(this,"pause")):i8(this,"pause"),h8(this,2,$7(e8(this))),this.V("remotePlayerChange")):f8(this,this.pause)};
g.h.WF=function(a){if(1==this.o){if(this.A){var b=e8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.qb()||3==b.o?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.z,j8(this,"seekTo",{newTime:a}))}else i8(this,"seekTo",{newTime:a});h8(this,3,a);this.V("remotePlayerChange")}else f8(this,g.Fa(this.WF,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.z,j8(this,"stopVideo")):i8(this,"stopVideo");var a=e8(this);a.index=-1;a.videoId="";X7(a);g8(this,a);this.V("remotePlayerChange")}else f8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=e8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.A)(function(){n7("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.hc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.A)(function(){n7("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.hc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);i8(this,"setVolume",e)}c.muted=b;c.volume=a;g8(this,c)}else f8(this,g.Fa(this.setVolume,a,b))};
g.h.WE=function(a,b){if(1==this.o){var c=e8(this),d={videoId:a};b&&(c.A={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Kg(b.style),g.ic(d,c.A));i8(this,"setSubtitlesTrack",d);g8(this,c)}else f8(this,g.Fa(this.WE,a,b))};
g.h.Ew=function(a,b){if(1==this.o){i8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Jb.id});var c=e8(this);c.audioTrackId=b.Jb.id;g8(this,c)}else f8(this,g.Fa(this.Ew,a,b))};
g.h.VF=function(a,b){if(1==this.o){if(a&&b){var c=e8(this);a8(c,a,b);g8(this,c)}i8(this,"previous")}else f8(this,g.Fa(this.VF,a,b))};
g.h.UF=function(a,b){if(1==this.o){if(a&&b){var c=e8(this);a8(c,a,b);g8(this,c)}i8(this,"next")}else f8(this,g.Fa(this.UF,a,b))};
g.h.Wy=function(){1==this.o?i8(this,"dismissAutoplay"):f8(this,this.Wy)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.V("proxyStateChange",a,this.o)}d8.ea.dispose.call(this)};
g.h.X=function(){nFa(this);this.C=null;this.D.clear();c8(this,null);d8.ea.X.call(this)};
g.h.Fw=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.HC(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.gU=function(a,b){this.V(a,b)};
g.h.ER=function(a){if(!a)this.Jm(null),c8(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=e8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)n7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,g8(this,b)}};
g.h.Jm=function(a){n7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),oFa(this),this.V("remotePlayerChange")};
g.h.DR=function(a){a?(oFa(this),this.V("remotePlayerChange")):this.Jm(null)};
g.h.QR=function(){var a=kFa();a&&c8(this,a)};
g.h.hc=function(a){n7("CP",a)};g.B(k8,g.YF);g.h=k8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.u(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.u(k)&&(l.currentIndex=k);c&&(this.gb.listId=c);this.gb.videoId=d;this.gb.index=k||0;this.gb.state=3;Z7(this.gb,m);this.C="UNSUPPORTED";l8("Connecting with setPlaylist and params: "+g.Kg(l));this.o.connect({method:"setPlaylist",
params:g.Kg(l)},a,KDa())}else l8("Connecting without params"),this.o.connect({},a,KDa());qFa(this)};
g.h.dispose=function(){this.ma()||(this.V("beforeDispose"),m8(this,3));k8.ea.dispose.call(this)};
g.h.X=function(){n8(this);p8(this);o8(this);g.pE(this.J);this.J=window.NaN;g.pE(this.K);this.K=window.NaN;this.B=null;g.IF(this.T);this.T.length=0;this.o.dispose();k8.ea.X.call(this);this.C=this.G=this.A=this.gb=this.o=null};
g.h.GK=function(){this.F(2)};
g.h.IR=function(){l8("Channel opened");this.O&&(this.O=!1,o8(this),this.M=g.nE((0,g.A)(function(){l8("Timing out waiting for a screen.");this.F(1)},this),15E3));
ODa(AEa(this.o),this.ba)};
g.h.FR=function(){l8("Channel closed");(0,window.isNaN)(this.D)?A6(!0):A6();this.dispose()};
g.h.GR=function(a){A6();(0,window.isNaN)(this.H())?(l8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,l8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),m8(this,2))};
g.h.HR=function(a){a.params?l8("Received: action="+a.action+", params="+g.Kg(a.params)):l8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.nx(a.params.devices);this.A=(0,g.I)(a,function(a){return new o6(a)});
a=!!g.La(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
tFa(this,a);break;case "loungeScreenDisconnected":g.Va(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
tFa(this,!1);break;case "remoteConnected":var b=new o6(g.nx(a.params.device));g.La(this.A,function(a){return b?a.id==b.id:!1})||g.Sa(this.A,b);
break;case "remoteDisconnected":b=new o6(g.nx(a.params.device));g.Va(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":vFa(this,a);break;case "nowPlaying":xFa(this,a);break;case "onStateChange":wFa(this,a);break;case "onAdStateChange":yFa(this,a);break;case "onVolumeChanged":zFa(this,a);break;case "onSubtitlesTrackChanged":uFa(this,a);break;case "nowAutoplaying":AFa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.V("autoplayModeChange",this.C);"DISABLED"==this.C&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":BFa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:l8("Unrecognized action: "+a.action)}};
g.h.mW=function(){if(this.B){var a=this.B;this.B=null;this.gb.videoId!=a&&q8(this,"getNowPlaying")}};
k8.prototype.subscribe=k8.prototype.subscribe;k8.prototype.unsubscribeByKey=k8.prototype.Yd;k8.prototype.ia=function(){var a=3;this.ma()||(a=0,(0,window.isNaN)(this.H())?i7(this.o)&&(0,window.isNaN)(this.D)&&(a=1):a=2);return a};
k8.prototype.getProxyState=k8.prototype.ia;k8.prototype.F=function(a){l8("Disconnecting with "+a);n8(this);this.V("beforeDisconnect",a);1==a&&A6();BEa(this.o,a);this.dispose()};
k8.prototype.disconnect=k8.prototype.F;k8.prototype.ha=function(){var a=this.gb;this.B&&(a=this.gb.clone(),a8(a,this.B,a.index));return b8(a)};
k8.prototype.getPlayerContextData=k8.prototype.ha;
k8.prototype.oa=function(a){var b=new W7(a);b.videoId&&b.videoId!=this.gb.videoId&&(this.B=b.videoId,g.pE(this.J),this.J=g.nE((0,g.A)(this.mW,this),5E3));var c=[];this.gb.listId==b.listId&&this.gb.videoId==b.videoId&&this.gb.index==b.index||c.push("remoteQueueChange");this.gb.o==b.o&&this.gb.volume==b.volume&&this.gb.muted==b.muted&&$7(this.gb)==$7(b)&&g.Kg(this.gb.A)==g.Kg(b.A)||c.push("remotePlayerChange");this.gb.reset(a);(0,g.C)(c,function(a){this.V(a)},this)};
k8.prototype.setPlayerContextData=k8.prototype.oa;k8.prototype.Z=function(){var a=this.o.F.id,b=g.La(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
k8.prototype.getOtherConnectedRemoteId=k8.prototype.Z;k8.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.G)():window.NaN};
k8.prototype.getReconnectTimeout=k8.prototype.H;k8.prototype.aa=function(){return this.C||"UNSUPPORTED"};
k8.prototype.getAutoplayMode=k8.prototype.aa;k8.prototype.da=function(){return this.G||""};
k8.prototype.getAutoplayVideoId=k8.prototype.da;k8.prototype.va=function(){if(!(0,window.isNaN)(this.H())){var a=this.o.A;g.qu(a.o);a.start()}};
k8.prototype.reconnect=k8.prototype.va;k8.prototype.ka=function(a,b){q8(this,a,b);sFa(this)};
k8.prototype.sendMessage=k8.prototype.ka;g.B(r8,r7);g.h=r8.prototype;g.h.te=function(a){return this.hd.$_gs(a)};
g.h.contains=function(a){return!!this.hd.$_c(a)};
g.h.get=function(a){return this.hd.$_g(a)};
g.h.start=function(){this.hd.$_st()};
g.h.add=function(a,b,c){this.hd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.hd.$_r(a,b,c)};
g.h.Oq=function(a,b,c,d){this.hd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.A.length;a<b;++a)this.hd.$_ubk(this.A[a]);this.A.length=0;this.hd=null;r8.ea.X.call(this)};
g.h.KX=function(){this.V("screenChange")};
g.h.FT=function(){this.V("onlineScreenChange")};
A7.prototype.$_st=A7.prototype.start;A7.prototype.$_gspc=A7.prototype.LX;A7.prototype.$_gsppc=A7.prototype.ZF;A7.prototype.$_c=A7.prototype.contains;A7.prototype.$_g=A7.prototype.get;A7.prototype.$_a=A7.prototype.add;A7.prototype.$_un=A7.prototype.Oq;A7.prototype.$_r=A7.prototype.remove;A7.prototype.$_gs=A7.prototype.te;A7.prototype.$_gos=A7.prototype.YF;A7.prototype.$_s=A7.prototype.subscribe;A7.prototype.$_ubk=A7.prototype.Yd;var s8=null,t8=null,I8=null,x8=[];g.t(J8,g.M);g.h=J8.prototype;
g.h.X=function(){g.M.prototype.X.call(this);this.C.stop();this.D.stop();this.L.stop();this.O();this.o.unsubscribe("proxyStateChange",this.CD,this);this.o.unsubscribe("remotePlayerChange",this.Mm,this);this.o.unsubscribe("remoteQueueChange",this.Tp,this);this.o.unsubscribe("autoplayUpNext",this.aD,this);this.o.unsubscribe("previousNextChange",this.zD,this);this.o.unsubscribe("nowAutoplaying",this.rD,this);this.o.unsubscribe("autoplayDismissed",this.ZC,this);this.o=this.H=null};
g.h.YB=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(M8(this)){if(!e8(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":e8(this.o).qb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.Xj(c[0],c[1]);break;case "control_subtitles_set_track":N8(this,c[0]);break;case "control_set_audio_track":c=c[0],M8(this)&&this.o.Ew(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();O8(this,0==c?void 0:c);break;case "control_seek":O8(this,c[0]);break;case "control_subtitles_set_track":N8(this,c[0]);break;case "control_set_audio_track":c=c[0],M8(this)&&this.o.Ew(this.A.getVideoData(1).videoId,c)}};
g.h.CR=function(a){this.L.BK(a)};
g.h.lX=function(a){this.YB("control_subtitles_set_track",g.$b(a)?null:a)};
g.h.mF=function(){var a=this.A.Ac("captions","track");g.$b(a)||N8(this,a)};
g.h.pD=function(a){if(M8(this)){this.o.unsubscribe("remotePlayerChange",this.Mm,this);var b=Math.round(a.volume);a=!!a.muted;var c=e8(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.M.start();this.o.subscribe("remotePlayerChange",this.Mm,this)}};
g.h.YS=function(){g.$b(this.F)||NFa(this,this.F);this.G=!1};
g.h.CD=function(a,b){this.D.stop();2==b&&this.jF()};
g.h.Mm=function(){if(M8(this)){this.C.stop();var a=e8(this.o);switch(a.o){case 1081:case 1:L8(this,new g.kQ(8));this.iF();break;case 1085:case 3:L8(this,new g.kQ(9));break;case 1083:case 0:L8(this,new g.kQ(2));this.K.stop();K8(this,this.A.getVideoData().lengthSeconds);break;case 1084:L8(this,new g.kQ(4));break;case 2:L8(this,new g.kQ(4));K8(this,$7(a));break;case -1:L8(this,new g.kQ(64));break;case -1E3:L8(this,new g.kQ(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=
e8(this.o).A;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.F=a,NFa(this,a));a=e8(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.M.isActive()||this.IF()}else MFa(this)};
g.h.zD=function(){this.A.V("mdxpreviousnextchange")};
g.h.Tp=function(){M8(this)||MFa(this)};
g.h.FJ=function(){this.o.Wy()};
g.h.aD=function(a){a&&(a=g.EE("/watch_queue_ajax",{method:"GET",dd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.kV,this)}))&&(this.O=(0,g.A)(a.abort,a))};
g.h.kV=function(a,b){var c=new g.pP({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.V("mdxautoplayupnext",c)};
g.h.rD=function(a){(0,window.isNaN)(a)||this.A.V("mdxnowautoplaying",a)};
g.h.ZC=function(){this.A.V("mdxautoplaycanceled")};
g.h.BP=function(a,b){-1==e8(this.o).o?O8(this,a):b&&this.o.WF(a)};
g.h.IF=function(){if(M8(this)){var a=e8(this.o);this.B.Ha(this.T);a.muted?this.A.mute():this.A.kg();this.A.setVolume(a.volume);this.T=this.B.R(this.A,"onVolumeChange",this.pD)}};
g.h.iF=function(){this.C.stop();if(!this.o.ma()){var a=e8(this.o);a.qb()&&L8(this,new g.kQ(8));K8(this,$7(a));this.C.start()}};
g.h.jF=function(){this.D.stop();this.C.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!(0,window.isNaN)(a)&&this.D.start()};g.t(P8,g.W);P8.prototype.D=function(a){PFa(this,a.state)};g.t(Q8,g.kZ);Q8.prototype.L=function(){var a=this.A.Ac("remote","receivers");a&&1<a.length&&!this.A.Ac("remote","quickCast")?(this.J=g.lb(a,this.F,this),g.lZ(this,(0,g.I)(a,this.F)),a=this.A.Ac("remote","currentReceiver"),this.Af(this.F(a)),this.enable(!0)):this.enable(!1)};
Q8.prototype.F=function(a){return a.key};
Q8.prototype.zf=function(a){return"cast-selector-receiver"==a?"Cast...":this.J[a].name};
Q8.prototype.zd=function(a){g.kZ.prototype.zd.call(this,a);this.A.Td("remote","currentReceiver",this.J[a]);this.D.Tb()};g.t(R8,g.GU);g.h=R8.prototype;g.h.create=function(){GFa(g.tN(g.Y(this.o)));this.F.push(g.jG("yt-remote-before-disconnect",this.xR,this));this.F.push(g.jG("yt-remote-connection-change",this.qU,this));this.F.push(g.jG("yt-remote-receiver-availability-change",this.AD,this));this.F.push(g.jG("yt-remote-auto-connect",this.oU,this));this.F.push(g.jG("yt-remote-receiver-resumed",this.nU,this));this.AD()};
g.h.load=function(){this.o.Bu();g.GU.prototype.load.call(this);this.D=new J8(this,this.o,this.A);var a=(a=LFa())?a.currentTime:0;var b=H8()?new d8(C8(),void 0):null;0==a&&b&&(a=$7(e8(b)));0!=a&&(this.J=a||0,this.o.V("progresssync",a,void 0));OFa(this,this.G,this.G);g.L_(this.o.app,6)};
g.h.unload=function(){this.o.V("mdxautoplaycanceled");this.C=this.B;g.mf(this.D,this.A);this.A=this.D=null;g.GU.prototype.unload.call(this);g.L_(this.o.app,5)};
g.h.X=function(){g.kG(this.F);g.GU.prototype.X.call(this)};
g.h.Cm=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.D.YB.apply(this.D,[a].concat(g.oa(c)))};
g.h.wK=function(){return this.loaded?this.D.suggestion:null};
g.h.ag=function(){return this.A?e8(this.A).ag:!1};
g.h.hasNext=function(){return this.A?e8(this.A).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.pP=function(){var a=e8(this.A),b=this.o.getVideoData();return{allowSeeking:this.o.jd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+Y7(a):a.C,isPeggedToLive:1>=(a.F?a.B+Y7(a):a.B)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.F?a.B+Y7(a):a.B,seekableStart:0<a.D?a.D+Y7(a):a.D}};
g.h.qP=function(){this.A&&this.A.UF()};
g.h.rP=function(){this.A&&this.A.VF()};
g.h.xR=function(a){1==a&&(this.K=this.A?e8(this.A):null)};
g.h.qU=function(){var a=H8()?new d8(C8(),void 0):null;if(a){var b=this.C;this.loaded&&this.unload();this.A=a;this.K=null;b.key!=this.B.key&&(this.C=b,this.load())}else g.lf(this.A),this.A=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.o.getVideoData().videoId&&this.o.BB(a.videoId,$7(a)));this.o.V("videodatachange","newdata",this.o.getVideoData(),3)};
g.h.AD=function(){this.H=[this.B].concat(IFa());var a=D8()||this.B;S8(this,a);this.o.xa("onMdxReceiversChange")};
g.h.oU=function(){var a=D8();S8(this,a)};
g.h.nU=function(){this.C=D8()};
g.h.oP=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?U7():S8(this,b)),this.loaded?this.C:this.B;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&U7(),!0):!1}};
g.h.sP=function(){i8(this.A,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Dc=function(){return!1};g.xX.remote=R8;})(_yt_player);
